# PyTorch Basic
PyTorch 기초 사용법

In [1]:
import numpy as np
import torch

In [4]:
np.arange(9)
##torch는 numpy와 정말 비슷해서 np를 torch로 바꾸기만 하면 된다.
nums = torch.arange(9)
#shape라 해도 되고, size라 해도 된다.
nums.shape

torch.Size([9])

In [5]:
#numpy로 타입 변환이 정말 쉽다.
type(nums)

torch.Tensor

In [7]:
nums.numpy()

array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int64)

In [9]:
#numpy와 같이 reshape가 가능하다.
nums.reshape(3,3)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [11]:
randoms = torch.rand((3,3))
randoms

tensor([[0.2855, 0.5813, 0.0392],
        [0.6966, 0.4989, 0.9603],
        [0.5676, 0.4063, 0.9499]])

In [13]:
zeros = torch.zeros((3,3))
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [14]:
ones = torch.ones((3,3))
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [15]:
#ones 사이즈와 같은 zeros들을 만들 수 있다.
torch.zeros_like(ones)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [16]:
zeros.size()

torch.Size([3, 3])

In [ ]:
#numpy와 torch를 구분하기 힘들 정도로 서로 잘 호환된다.

# Operation
Pytorch 수학 연산

In [17]:
nums * 3

tensor([ 0,  3,  6,  9, 12, 15, 18, 21, 24])

In [23]:
nums = nums.reshape((3,3))
nums + nums

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [24]:
#이렇게도 더할 수 있다.
result = torch.add(nums,10)

In [25]:
#변환이 너무 쉽다.
result.numpy()

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]], dtype=int64)

# View

In [26]:
range_nums = torch.arange(9).reshape((3,3))
range_nums

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [27]:
#view는 reshape와 다를 게 없다, 권장에도 reshape를 하라고 하지만,
#공식 홈페이지에서 사용한 경우들이 있으니 보자
range_nums.view(-1)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [28]:
range_nums.view((1,9))

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

# Slice and Index

In [29]:
nums

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [30]:
#파이썬 슬라이싱과 다를바없다
nums[1]

tensor([3, 4, 5])

In [36]:
nums[0:3]

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [37]:
nums[1:,1:]

tensor([[4, 5],
        [7, 8]])

In [38]:
nums[1:,:]

tensor([[3, 4, 5],
        [6, 7, 8]])

# Compile
numpy를 torch tensor로 불러오기
numpy와 다른 점

In [39]:
#numpy에서 pytorch로 넘기기
arr = np.array([1,1,1])
arr_torch = torch.from_numpy(arr)
arr_torch.float()

tensor([1., 1., 1.])

In [41]:
#gpu device 관리가 중요하다.
#자동으로 gpu가 있다면, cuda로 넘어가도록 할 수 잇다. 공식홈페이지에 있다.
device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [42]:
arr_torch.to(device)

tensor([1, 1, 1], dtype=torch.int32)

In [43]:
device

'cpu'

# AutoGrad

In [45]:
#기울기를 얻어서, 학습이 되도록 만드는 것이다.
x = torch.ones(2,2, requires_grad=True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [46]:
y = x + 2
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [47]:
print(y.grad_fn)

In [52]:
z = y * y * 3
out = z.mean()

In [56]:
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [59]:
out.backward()

In [63]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [65]:
print(x.requires_grad)
print((x ** 2).requires_grad)

True
True


In [66]:
#이렇게 만들면 batch normalization, dropout 도 안하고 기울기도 안구하기 때문에 
#test모드일 때 사용하면 속도가 훨씬 빠르다.
with torch.no_grad():
    print((x ** 2).requires_grad)

False
