In [2]:
import numpy as np
import tensorflow as tf


# Tensor 생성


In [3]:
arr = np.array([1,2,3])

In [4]:
arr.shape

(3,)

In [5]:
arr = np.array([[1,2,3],[1,2,3]])

In [6]:
arr.shape

(2, 3)

In [7]:
#텐서 생성
tf.constant([1,2,3])

<tf.Tensor: id=0, shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [10]:
#튜플을 넣어서 텐서 생성도 가능하다.
tf.constant(((1,2,3),(1,2,3)))

<tf.Tensor: id=1, shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [1, 2, 3]])>

In [11]:
#보통 numpy array를 다루기 때문에 array에 대해서 잘아는 것이 중요하다.
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [12]:
tf.constant(arr)

<tf.Tensor: id=2, shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [13]:
tensor = tf.constant([1,2,3])

In [14]:
tensor

<tf.Tensor: id=3, shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [15]:
tensor.shape
#1차원에 3개의 element 이다. np array와 같다.

TensorShape([3])

In [17]:
#data type 확인 , 우리가 정수로 넣어줬으니 int32로 반환 된다.
#data type마다 모델의 무게나 성능 차이에도 영향을 줄 수 있다.
tensor.dtype

tf.int32

In [20]:
#바로 dtype 정의해주기
tensor = tf.constant([1,2,3], dtype=tf.float32)
tensor

<tf.Tensor: id=6, shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [23]:
#numpy는 astype로 데이터 변환을 했지만, 여기서는 tf.cast를 사용한다.
arr = np.array([1,2,3] , dtype=np.float32)
arr.astype(np.uint8)

array([1, 2, 3], dtype=uint8)

In [25]:
tf.cast(tensor, dtype=tf.uint8)

<tf.Tensor: id=7, shape=(3,), dtype=uint8, numpy=array([1, 2, 3], dtype=uint8)>

In [26]:
# tensor안에 있는 numpy 불러오기
tensor.numpy()

array([1., 2., 3.], dtype=float32)

In [27]:
#이렇게 해도 된다.
np.array(tensor)

array([1., 2., 3.], dtype=float32)

In [28]:
type(tensor)

tensorflow.python.framework.ops.EagerTensor

In [29]:
type(np.array(tensor))

numpy.ndarray

In [33]:
# 난수 생성
#np.random.randn() - normal distributiuon이다.
#tensorflow는 normal distribution과 uniform distribution으로 나뉜다.

np.random.randn(9)
#normal distribution
tf.random.normal([3,3])


<tf.Tensor: id=32, shape=(3, 3), dtype=float32, numpy=
array([[-0.4063333 ,  0.32572672,  0.5553086 ],
       [ 0.1935811 ,  1.2179337 , -1.6166717 ],
       [-1.3373032 , -1.6641592 , -1.7777816 ]], dtype=float32)>

In [34]:
#uniform distributionm
tf.random.uniform([4,4])

<tf.Tensor: id=39, shape=(4, 4), dtype=float32, numpy=
array([[0.0061177 , 0.15936244, 0.61920774, 0.14936066],
       [0.58052754, 0.9053047 , 0.91712356, 0.14138997],
       [0.6582824 , 0.5709976 , 0.81883216, 0.6829114 ],
       [0.4365313 , 0.36452913, 0.51382256, 0.45241034]], dtype=float32)>